CREATE DATABASE University;
Go

USE University;
Go 

CREATE TABLE [dbo].[GROUP]
(
    ID INT PRIMARY KEY  IDENTITY(1, 1) NOT NULL,
    COURSEID INT,
    NAME VARCHAR(50)
);
Go


CREATE TABLE COURSE (
    ID INT PRIMARY KEY  IDENTITY(1, 1) NOT NULL,
    NAME VARCHAR(50),
    DESCRIPTION VARCHAR(255)
);
Go

CREATE TABLE STUDENT (
    ID INT PRIMARY KEY  IDENTITY(1, 1) NOT NULL,
    GROUPID INT,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50)
);
Go

ALTER TABLE GROUPE
ADD CONSTRAINT FK_GROUPS_COURSE
FOREIGN KEY (COURSEID)
REFERENCES COURSE(COURSEID);
Go

ALTER TABLE STUDENT
ADD CONSTRAINT FK_GROUP
FOREIGN KEY (GROUPID)
REFERENCES GROUPE(GROUPID);
Go

ALTER TABLE [dbo].[GROUP]
ADD CONSTRAINT UQ_GROUPS_NAME UNIQUE (NAME);
GO

ALTER TABLE COURSE
ADD CONSTRAINT UQ_COURSE_NAME UNIQUE (NAME);
GO