
SELECT C.NAME AS CourseName, S.FIRST_NAME, S.LAST_NAME
FROM COURSE C
JOIN GROUPS G ON C.ID = G.COURSE_ID_FK
JOIN STUDENTS S ON G.ID = S.GROUP_ID_FK;

DELETE FROM STUDENTS
WHERE GROUP_ID_FK = (
    SELECT ID
    FROM GROUPS
    WHERE NAME = 'SR-01'
);

SELECT G.NAME, COUNT(S.ID) AS StudentCount
FROM GROUPS G
LEFT JOIN STUDENTS S ON G.ID = S.GROUP_ID_FK
GROUP BY G.ID, G.NAME
HAVING COUNT(S.ID) < 10;